list Set

data Lifespan 
  = Immortal {} 
  | Limited { max: Int? }

data Power
  = Shapeshifting {}
  | Thunderbolt {}

resolver God = {
  name: String
  power: Set<Power>
  lifespan: Lifespan
}

resolver Deity
  = God
  | Titan { name: String } # exists only inside Deity
  | Unknown {} # exists only inside of Deity`

resolver Query = {
  deities(lifespan: Lifespan?): [Deity]
}