
data Lifespan 
  = Immortal {} 
  | Limited { max: Int? }

data Power
  = Shapeshifting {}
  | Thunderbolt {}

resolver God = {
  name: String
  power: [Power]
}

resolver Deity
  = God
  | Titan { name: String } # exists only inside Deity
  | Monsters {} # exists only inside of Deity`

resolver Query = {
  deities(lifespan: Lifespan?): [Deity]
}