resolver Query = {
  name: String
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

resolver Mutation = {
  name: String
}

resolver Subscription = {
  name: String
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
