{
  characters {
    ...OnCharacter
    ...onDeity
    ...onHero
  }
}

fragment OnCharacter on CharacterFields {
  name
}

fragment onDeity on Deity {
  power
}

fragment onHero on Hero {
  nickname
}
