directive @DirectiveA(a1: String) on SCALAR

directive @DirectiveC(arg: Int) on ARGUMENT_DEFINITION

data MyEnum = EnumA

resolver MyType @SomeDirective {
  field(a1: Int? @DirectiveC(arg: True, someargs: 1)): String? @DirectiveC
}

data Input @include {
  field: ID? @skip
}

resolver Query @DirectiveC(arg: "bla") {
  field(a1: Int): Int @skip
}
