query {
  nested(
    data: 
      [
        [1, 
          [
            [ "k1", { id: "123" }], 
            [ "k1", { id: "124" }]
          ]
        ],
        [2, 
          [
            [ "k1", { id: "234", name: "David" }], 
            [ "k2", { id: "235", name: "George" }]
          ]
        ]
      ]
  )
}
