resolver Query {
  deity(name: String?): Deity
}

resolver Character {
  name(id: ID?): String
}

resolver Hero {
  # arg: id has weeker type
  power(id: ID?): String
}

resolver HeroUnion | Character = Hero

resolver Supernatural {
  name(id: ID?): String
  power(id: ID): [String]
}

resolver Deity {
  # undefined args (id: String)
  name: String
  # arg: id has different type
  power(id: String): [String]
}

resolver DeityUnion | Supernatural = Deity
