directive @MyDirective(name: String?) on FIELD | QUERY

resolver Deity = {
  name: String
  power: [String]
  friends: [Deity]
}

resolver Query = {
  deity(name: String?): Deity
}

resolver Mutation = {
  deity(name: String?): Deity
}

resolver Subscription = {
  deity(name: String?): Deity
}