directive @MyDirective(name: String?) on FIELD | QUERY

resolver Deity = {
  name: String
  power: [String]
  friends: [Deity]
}

resolver Query = {
  deity(name: String?): Deity
}

schema {
  query: Query
  mutation: Query
  subscription: Query
}
