scalar MyScalar

data MyEnum = A {} | B {}

data Input = {
  id: String 
  int: MyScalar
}

resolver Deity = {
  name(i: Input?, arg: MyEnum?, list: [Input]?): String
  power: [String]
}

resolver Query = {
  simple(name: String?): Deity
}

resolver Mutation = Query

resolver Subscription = Query

